version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_CONNECTION_STRING='mongodb://mongodb:27018/d6s'
  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    command: mongod --port 27018